using Microsoft.EntityFrameworkCore;
using VulnerableApp.Api.Data;
using VulnerableApp.Api.Models;
using Xunit;

namespace VulnerableApp.Tests;

// VULN-011: MT-003 P2 — Tests verify orders are returned but never assert
// that Tenant A cannot access Tenant B's data. The global query filter
// (which is itself missing — VULN-007) is not exercised by these tests.
public class OrderRepositoryTests
{
    [Fact]
    public async Task GetByStatus_ReturnsMatchingOrders()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase("TestDb")
            .Options;

        using var ctx = new AppDbContext(options);
        ctx.Orders.Add(new Order { Id = 1, UserId = 1, TenantId = 1, Status = "Active", Total = 100 });
        ctx.Orders.Add(new Order { Id = 2, UserId = 1, TenantId = 1, Status = "Closed", Total = 50 });
        await ctx.SaveChangesAsync();

        var repo = new OrderRepository(ctx);
        var result = await repo.GetByStatusAsync("Active");

        Assert.Single(result);
        Assert.Equal("Active", result[0].Status);

        // Missing cross-tenant assertion — Tenant 2 orders are not seeded and
        // there is no test that calls GetByStatusAsync as Tenant 2 to verify
        // that Tenant 1's orders are invisible.
        //
        // Required test (generated by sql-multitenancy skill):
        // Assert.All(result, o => Assert.Equal(currentTenantId, o.TenantId));
    }
}
